/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import Classes.Book;
import Classes.Subject;

/**
 *
 * @author King The Shepherd
 */
public class AssignBooksUI extends javax.swing.JFrame {

    /**
     * Creates new form AssignBooksUI
     */
    public AssignBooksUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txfGrade = new javax.swing.JTextField();
        txfSubject = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfNoOfStudents = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfNoOfBooks = new javax.swing.JTextField();
        btnGetQuantites = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaStudentBookNumbers = new javax.swing.JTextArea();
        radForEnireGrade = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Grade");

        jLabel2.setText("Subject");

        jLabel3.setText("Number Of Students In Class Or Registered");

        jLabel4.setText("Number Of books");

        btnGetQuantites.setText("Get Book And Student Quantities");
        btnGetQuantites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetQuantitesActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txaStudentBookNumbers.setColumns(20);
        txaStudentBookNumbers.setRows(5);
        jScrollPane1.setViewportView(txaStudentBookNumbers);

        radForEnireGrade.setText("Assign For Entire Grade");
        radForEnireGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radForEnireGradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txfNoOfBooks))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txfSubject))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(btnAssign)
                                    .addComponent(txfNoOfStudents)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radForEnireGrade)
                            .addComponent(btnGetQuantites))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txfGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(radForEnireGrade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGetQuantites)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txfNoOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txfNoOfStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAssign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
    boolean ForEntireGrade = radForEnireGrade.isSelected();
    
    if(ForEntireGrade == false){
    String Grade = txfGrade.getText();
    String Subject = txfSubject.getText();
   
    
    int GradeCode = Classes.UtilityClass.getGradeCode(Grade);
    Subject subject = new Subject(Subject);
    
    Book book = new Book(GradeCode, subject.getSubjectCode());
    
    txaStudentBookNumbers.append(book.assignBooks(Grade, Subject, ForEntireGrade));
    }
    
    if(ForEntireGrade == true){
    
    String Grade = txfGrade.getText();
    String Subject = txfSubject.getText();
   
    
    int GradeCode = Integer.parseInt(Grade);
    Subject subject = new Subject(Subject);
    
    Book book = new Book(GradeCode, subject.getSubjectCode());
    
    txaStudentBookNumbers.append(book.assignBooks(Grade, Subject, ForEntireGrade));
    }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void radForEnireGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radForEnireGradeActionPerformed
     
    }//GEN-LAST:event_radForEnireGradeActionPerformed

    private void btnGetQuantitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetQuantitesActionPerformed
boolean forEntireGrade;

forEntireGrade = radForEnireGrade.isSelected();
if(forEntireGrade == false){
int gradeCode = Classes.UtilityClass.getGradeCode(txfGrade.getText());//Getting Of Grade Code

Subject subject = new Subject(txfSubject.getText());
String SubjectCode = subject.getSubjectCode();

int noOfBooks= Book.getNoOfBooks(SubjectCode, gradeCode);


int noOfStudents = Book.getNoOfStudents(txfGrade.getText(), forEntireGrade);

txfNoOfStudents.setText(Integer.toString(noOfStudents));
txfNoOfBooks.setText(Integer.toString(noOfBooks));
}

if(forEntireGrade == true){
int gradeCode = Integer.parseInt(txfGrade.getText());//Getting Of Grade Code

Subject subject = new Subject(txfSubject.getText());
String SubjectCode = subject.getSubjectCode();

int noOfBooks= Book.getNoOfBooks(SubjectCode, gradeCode);


int noOfStudents = Book.getNoOfStudents(txfGrade.getText(), forEntireGrade);

txfNoOfStudents.setText(Integer.toString(noOfStudents));
txfNoOfBooks.setText(Integer.toString(noOfBooks));
}

    }//GEN-LAST:event_btnGetQuantitesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GUIs.swtchOver.switchOver();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignBooksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignBooksUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnGetQuantites;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radForEnireGrade;
    private javax.swing.JTextArea txaStudentBookNumbers;
    private javax.swing.JTextField txfGrade;
    private javax.swing.JTextField txfNoOfBooks;
    private javax.swing.JTextField txfNoOfStudents;
    private javax.swing.JTextField txfSubject;
    // End of variables declaration//GEN-END:variables
}
