/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

/**
 *
 * @author micheal chipiko
 */
public class TeacherMainMenuUI extends javax.swing.JFrame {

    /**
     * Creates new form TeacherMainMenuUI
     */
    public TeacherMainMenuUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewTextBook = new javax.swing.JButton();
        btnAssignTextBooks = new javax.swing.JButton();
        btnUpdateLogin = new javax.swing.JButton();
        btnUpdateTeacherInfo = new javax.swing.JButton();
        btnAddMarks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu (TeacherMode)");

        btnNewTextBook.setText("Add new subject text book");
        btnNewTextBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTextBookActionPerformed(evt);
            }
        });

        btnAssignTextBooks.setText("Assign Text Books");
        btnAssignTextBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignTextBooksActionPerformed(evt);
            }
        });

        btnUpdateLogin.setText("Update Login Details");
        btnUpdateLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLoginActionPerformed(evt);
            }
        });

        btnUpdateTeacherInfo.setText("Update Personal Information");
        btnUpdateTeacherInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTeacherInfoActionPerformed(evt);
            }
        });

        btnAddMarks.setText("Add Marks");
        btnAddMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMarksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdateLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewTextBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAssignTextBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateTeacherInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnAddMarks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewTextBook)
                    .addComponent(btnAssignTextBooks))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateLogin)
                    .addComponent(btnUpdateTeacherInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnAddMarks)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateTeacherInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTeacherInfoActionPerformed
   UpdateTeacherInfoUI UTIUI = new UpdateTeacherInfoUI();
   UTIUI.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_btnUpdateTeacherInfoActionPerformed

    private void btnUpdateLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLoginActionPerformed
        new UpdateLogInInfoUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUpdateLoginActionPerformed

    private void btnNewTextBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTextBookActionPerformed
        new AddNewBookUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNewTextBookActionPerformed

    private void btnAssignTextBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignTextBooksActionPerformed
      new AssignBooksUI().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnAssignTextBooksActionPerformed

    private void btnAddMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarksActionPerformed
        new AddMarksUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddMarksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherMainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherMainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherMainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherMainMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherMainMenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMarks;
    private javax.swing.JButton btnAssignTextBooks;
    private javax.swing.JButton btnNewTextBook;
    private javax.swing.JButton btnUpdateLogin;
    private javax.swing.JButton btnUpdateTeacherInfo;
    // End of variables declaration//GEN-END:variables
}
